- hosts: node01
  become: true

  tasks:
    - name: installing packages
      yum:
        name: ['httpd','httpd-tools']
        state: "installed"

    - name: copying a file to /var/www/html
      copy:
        src: "index.html"
        dest: "/var/www/html/"

    - name: copying the configuration file
      template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf

    - name: Disabling selinux
      selinux:
        state: disabled 

    - name: Starting the service
      service:
        name: "httpd"
        state: "restarted"
      tags: restart

